config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  
  namespace :admin do
    root 'articles#index'
    resources :articles
  end

  resources :articles, only: [:index, :show] do
    resources :comments
  end
  resources :messages, only: :create

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  include Wisper::Publisher
  
  friendly_id :title, use: :slugged

  has_many :comments, dependent: :delete_all
  has_one_attached :image

  validates :title, presence: true, length: { minimum: 3 }
  validates :text, presence: true, length: { minimum: 10 } 
  validates :author, :image, presence: true

  after_create :new_post_email

  scope :featured, -> { newest.first }
  scope :newest, -> { order(created_at: :desc) }

  private

  def new_post_email
    broadcast(:new_article_email)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Wisper::Publisher

  validates :body, :author_name, presence: true
  belongs_to :article

  after_create :comment_email

  private

  def comment_email
    broadcast(:new_comment_email, self.article.id)
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV.fetch('ADMIN_NAME'), password: ENV.fetch('ADMIN_PASSWORD')
    
  layout 'admin/application'
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :load_article, only: [:show, :edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.image.attach(article_params[:image])
    
    if @article.save
      redirect_to admin_articles_path, notice: "You successfully created a post."
    else
      flash[:alert] = "All fields are required."
      render :new
    end
  end

  def index
    @articles = Article.all 
  end

  def edit
  end

  def update
    
    if @article.update(article_params)
      redirect_to admin_articles_path, notice: "You successfully updated your post."
    else
      flash[:alert] = "Please fill in all required fields."
      render :edit
    end
  end

  def destroy
    @article.destroy
  
    redirect_to admin_articles_path, notice: "Your post has been been deleted."
  end

  private 
  def article_params 
    params.require(:article).permit(:title, :author, :text, :image)
  end
end

private
  def load_article
    @article = Article.friendly.find(params[:id])
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :user, :logged_in?

  def user
    session[:userinfo]
  end

  def logged_in?
    !!user
  end

  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  after_action :set_return_url, only: :show

  def show
    @article = Article.includes(:comments).friendly.find(params[:id])

    
    @comment = Comment.new
  end

  def index
    @articles = Article.newest

    @featured_article = Article.featured
  end

  private

  def set_return_url
    session[:return_url] = article_url(@article)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @article = Article.friendly.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
  
    if @comment.save
      redirect_to article_path(@comment.article)
    else
      render :new
    end
  end
  
  def comment_params
    params.require(:comment).permit(:author_name, :body, :image)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  skip_before_action :verify_authenticity_token

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      authorised: authorised?
    }
    result = PaulsBlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def authorised?
    token = request.authorization[7, request.authorization.length]
    decoded_token = JWT.decode(token, OpenSSL::PKey::RSA.new(ENV.fetch('AUTH0_CERTIFICATE')).public_key, true, { algorithm: 'RS256' })
    decoded_token.first.fetch("exp") >= Time.now.to_i
  rescue 
    false 
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(RougeRender, fenced_code_blocks: true)
    markdown.render(text).html_safe
  end
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>
  <%= render partial: "shared/form_errors", object: @article %>
  
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, required: :true, placeholder: "Add your title here", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, required: :true, placeholder: "Add your name here", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, required: :true, placeholder: "Add your article here", class: "form-control", rows: 10%>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-success btn-lg"%>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: 'form' %>

app/views/admin/articles/index.html.erb
  <h2 class="admin__h2">Articles</h2>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date-Created</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td><%= link_to article.title, admin_article_path(article), class: "table__links"%></td>
              <td><%= article.author %></td>
              <td><%= article.created_at.to_date %></td>
              <td><%= link_to 'Edit', edit_admin_article_path(article), class: "btn btn-warning"%></td>
              <td><%= link_to 'Delete', admin_article_path(article), 
                              method: :delete, 
                              data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
 
  <%= link_to 'New Post', new_admin_article_path, class: "btn btn-primary btn-lg" %>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render partial: 'form' %>



  

app/views/admin/articles/show.html.erb
<h1>Show Page</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @article.created_at %>
</p>

<%= link_to 'New Article', new_admin_article_path %><br>

<%= link_to 'Back to Articles', articles_path %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paul Brighton's Web Dev Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A blog by Paul Brighton all about web development. It includes articles about HTML, CSS, JavaScript and Ruby on Rails plus other tips on web design and developing." />
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <%= link_to "Paul's Blog Admin", admin_articles_path, class: "navbar-brand" %>
        <button class="navbar-toggler bg-dark" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <%= link_to "Articles", admin_articles_path, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item" >
              <%= link_to "New Article", new_admin_article_path, class: "nav-link text-dark" %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |name, msg| -%>
        <% if name == "alert" %>
          <%= content_tag :div, msg, class: "alert alert-danger" %>
        <% else %>
          <%= content_tag :div, msg, class: "alert alert-success" %>
        <% end %>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_comment-form.html.erb
  
<div class="c-comments-form">
  <%= render partial: "shared/form_errors", object: @comment %>
  <%= form_for [ @article, @comment ] do |f| %>
    <div>
      <%= f.label :name, class: "c-comments-form__name-label" %>
      <%= f.text_field :author_name, required: :true, placeholder: :"Add your name here", class: "c-comments-form__name-field" %>
    </div>
    <div>
      <%= f.label :comment, class: "c-comments-form__body-label" %>
      <%= f.text_area :body, required: :true, placeholder: :"Add your comment here", class: "c-comments-form__body-text" %>
    </div>
    <div>
      <%= f.submit 'Post', class: "c-comments-form__submit-btn" %>
    </div>
  <% end %>
</div>
    

app/views/shared/_form_errors.html.erb
<% if form_errors.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(form_errors.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% form_errors.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>    